# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    fix_invalid_geometries as fix_invalid_geometries,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_line_chart as draw_line_chart
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    envelope_gdf as envelope_gdf,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.transformation import explode as explode
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_mnc.tasks.io import get_patrol_values as get_patrol_values
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    fill_missing_values as fill_missing_values,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import filter_notna as filter_notna

get_patrol_observations_from_patrols_df = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrol_observations_from_patrols_df",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope_workflows_ext_big_life.tasks.results import draw_map as draw_map_2
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_mnc.tasks.io import (
    compute_patrol_occupancy as compute_patrol_occupancy,
)
from ecoscope_workflows_ext_mnc.tasks.io import (
    create_patrol_coverage_grid as create_patrol_coverage_grid,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    convert_columns_to_int as convert_columns_to_int,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    concatenate_dataframes as concatenate_dataframes,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.8,
                    "max_zoom": 20,
                },
                {
                    "url": "https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places_Alternate/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.35,
                    "max_zoom": 20,
                },
            ],
            **(params.get("configure_base_maps") or {}),
        )
        .call()
    )

    persist_mnc_gpkg = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("persist_mnc_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("persist_mnc_gpkg") or {}),
        )
        .call()
    )

    download_mnc_parcels = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("download_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("download_mnc_parcels") or {}),
        )
        .call()
    )

    load_comm_shp = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_comm_shp")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=persist_mnc_gpkg,
            layer=None,
            deserialize_json=False,
            **(params.get("load_comm_shp") or {}),
        )
        .call()
    )

    fix_comm_geom = (
        task(fix_invalid_geometries)
        .validate()
        .set_task_instance_id("fix_comm_geom")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=load_comm_shp, **(params.get("fix_comm_geom") or {}))
        .call()
    )

    filter_conservancy_boundary = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_conservancy_boundary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fix_comm_geom,
            column_name="grazing_zone",
            op="equal",
            value="Conservancy",
            reset_index=True,
            **(params.get("filter_conservancy_boundary") or {}),
        )
        .call()
    )

    filter_mara_north = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_mara_north")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fix_comm_geom,
            column_name="name",
            op="equal",
            value="Mara North Conservancy",
            reset_index=True,
            **(params.get("filter_mara_north") or {}),
        )
        .call()
    )

    load_mnc_parcels = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=download_mnc_parcels,
            layer=None,
            deserialize_json=False,
            **(params.get("load_mnc_parcels") or {}),
        )
        .call()
    )

    create_conservancy_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_conservancy_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=filter_conservancy_boundary,
            data_url=None,
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": [169, 169, 169, 255],
                "get_line_width": 1.75,
            },
            legend={
                "title": "",
                "values": [{"label": "Conservancy Boundary", "color": "#a9a9a9"}],
                "sort": None,
                "label_suffix": None,
            },
            **(params.get("create_conservancy_layer") or {}),
        )
        .call()
    )

    create_parcels_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_parcels_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=load_mnc_parcels,
            data_url=None,
            layer_style={
                "filled": True,
                "stroked": True,
                "get_fill_color": [189, 183, 107, 60],
                "get_line_color": [189, 183, 107, 255],
                "get_line_width": 1.5,
            },
            legend={
                "title": "Map Layers",
                "values": [{"label": "Parcels", "color": "#bdb76b"}],
                "sort": None,
                "label_suffix": None,
            },
            **(params.get("create_parcels_layer") or {}),
        )
        .call()
    )

    get_events_data = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            force_point_geometry=True,
            **(params.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        task(extract_column_as_type)
        .validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_temporal") or {}),
        )
        .call()
    )

    filter_events = (
        task(exclude_row_values)
        .validate()
        .set_task_instance_id("filter_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column="event_type",
            values=[
                "distancecountwildlife_rep",
                "distancecountpatrol_rep",
                "airstrip_operations",
            ],
            **(params.get("filter_events") or {}),
        )
        .call()
    )

    total_events_recorded = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("total_events_recorded")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=filter_events,
            **(params.get("total_events_recorded") or {}),
        )
        .call()
    )

    persist_tevents_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_tevents_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=total_events_recorded,
            filename="total_events_recorded_by_date",
            **(params.get("persist_tevents_df") or {}),
        )
        .call()
    )

    total_events_type_recorded = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("total_events_type_recorded")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date", "event_type"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=filter_events,
            **(params.get("total_events_type_recorded") or {}),
        )
        .call()
    )

    persist_summary_event_type = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_summary_event_type")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=total_events_type_recorded,
            filename="total_events_recorded_by_type",
            **(params.get("persist_summary_event_type") or {}),
        )
        .call()
    )

    draw_events_chart = (
        task(draw_line_chart)
        .validate()
        .set_task_instance_id("draw_events_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            smoothing=None,
            dataframe=total_events_recorded,
            x_column="date",
            y_column="no_of_events",
            category_column=None,
            line_kwargs={"shape": "linear", "color": "lightsteelblue"},
            layout_kwargs={
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": False,
                "fontsize": 10,
                "fontcolor": "#222222",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {
                    "title": "Date",
                    "tickformat": "%Y-%m-%d",
                    "tickangle": -45,
                    "rangemode": "auto",
                },
                "yaxis": {"title": "Number of events", "tickformat": ".1f"},
                "hovermode": "x unified",
            },
            **(params.get("draw_events_chart") or {}),
        )
        .call()
    )

    persist_total_events = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_events_chart,
            filename="total_events_recorded.html",
            **(params.get("persist_total_events") or {}),
        )
        .call()
    )

    convert_events_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_events_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_total_events,
            config={
                "width": 1280,
                "height": 720,
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "timeout": 0,
                "max_concurrent_pages": 5,
            },
            **(params.get("convert_events_chart_png") or {}),
        )
        .call()
    )

    events_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("events_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Events Recorded",
            data=persist_total_events,
            **(params.get("events_chart_widget") or {}),
        )
        .call()
    )

    zoom_to_envelope = (
        task(envelope_gdf)
        .validate()
        .set_task_instance_id("zoom_to_envelope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=filter_mara_north, **(params.get("zoom_to_envelope") or {}))
        .call()
    )

    gdf_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("gdf_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=zoom_to_envelope,
            **(params.get("gdf_image_extent") or {}),
        )
        .call()
    )

    filter_patrol_info_events = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_patrol_info_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="patrol_info",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_patrol_info_events") or {}),
        )
        .call()
    )

    process_patrol_events = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_patrol_info_events,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_patrol_events") or {}),
        )
        .call()
    )

    normalize_patrols = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_patrol_events,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_patrols") or {}),
        )
        .call()
    )

    drop_patrol_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_patrol_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_patrols,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_patrol_prefix") or {}),
        )
        .call()
    )

    persist_events = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="patrol_events",
            df=drop_patrol_prefix,
            **(params.get("persist_events") or {}),
        )
        .call()
    )

    rename_patrol_info = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_patrol_info")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "patrols": "patrol_id",
                "Participants": "participants",
                "Patrol Purpose": "patrol_purpose",
                "Transport Type": "transport_type",
            },
            df=drop_patrol_prefix,
            **(params.get("rename_patrol_info") or {}),
        )
        .call()
    )

    patrol_info_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("patrol_info_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_purpose"],
            summary_params=[
                {
                    "display_name": "number_of_patrols",
                    "aggregator": "nunique",
                    "column": "id",
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            df=rename_patrol_info,
            **(params.get("patrol_info_summary") or {}),
        )
        .call()
    )

    persist_patrol_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="patrol_purpose_summary",
            df=patrol_info_summary,
            **(params.get("persist_patrol_df") or {}),
        )
        .call()
    )

    patrol_summary_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("patrol_summary_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=patrol_info_summary,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Patrol Purpose Summary",
            **(params.get("patrol_summary_table_html") or {}),
        )
        .call()
    )

    patrol_summary_table_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_summary_table_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=patrol_summary_table_html,
            filename="patrol_purpose_summary_table.html",
            **(params.get("patrol_summary_table_url") or {}),
        )
        .call()
    )

    patrol_summary_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Purpose Summary",
            data=patrol_summary_table_url,
            **(params.get("patrol_summary_table_widget") or {}),
        )
        .call()
    )

    filter_null_patrols = (
        task(filter_notna)
        .validate()
        .set_task_instance_id("filter_null_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_patrol_info,
            column_names=["patrol_id"],
            **(params.get("filter_null_patrols") or {}),
        )
        .call()
    )

    fill_transport_type = (
        task(fill_missing_values)
        .validate()
        .set_task_instance_id("fill_transport_type")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_null_patrols,
            value="Undefined",
            subset=["transport_type"],
            **(params.get("fill_transport_type") or {}),
        )
        .call()
    )

    explode_patrol_id = (
        task(explode)
        .validate()
        .set_task_instance_id("explode_patrol_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fill_transport_type,
            column_name="patrol_id",
            ignore_index=True,
            **(params.get("explode_patrol_id") or {}),
        )
        .call()
    )

    get_patrol_event_values = (
        task(get_patrol_values)
        .validate()
        .set_task_instance_id("get_patrol_event_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events_df=explode_patrol_id,
            patrols_column="patrol_id",
            client=er_client_name,
            max_workers=10,
            **(params.get("get_patrol_event_values") or {}),
        )
        .call()
    )

    get_patrol_obs = (
        task(get_patrol_observations_from_patrols_df)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("get_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            patrols_df=get_patrol_event_values,
            include_patrol_details=True,
            raise_on_empty=True,
            sub_page_size=100,
            **(params.get("get_patrol_obs") or {}),
        )
        .call()
    )

    join_patrol_df = (
        task(map_columns)
        .validate()
        .set_task_instance_id("join_patrol_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=explode_patrol_id,
            drop_columns=[],
            retain_columns=[
                "id",
                "patrol_id",
                "participants",
                "patrol_purpose",
                "transport_type",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params.get("join_patrol_df") or {}),
        )
        .call()
    )

    merge_patrol_df_obs = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("merge_patrol_df_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=get_patrol_obs,
            right=join_patrol_df,
            on="patrol_id",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            how="inner",
            **(params.get("merge_patrol_df_obs") or {}),
        )
        .call()
    )

    explode_participants = (
        task(explode)
        .validate()
        .set_task_instance_id("explode_participants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=merge_patrol_df_obs,
            ignore_index=True,
            column_name="participants",
            **(params.get("explode_participants") or {}),
        )
        .call()
    )

    obs_relocs = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("obs_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=explode_participants,
            relocs_columns=[
                "extra__id",
                "extra__created_at",
                "extra__subject_id",
                "geometry",
                "groupby_col",
                "fixtime",
                "junk_status",
                "patrol_id",
                "patrol_title",
                "patrol_serial_number",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type",
                "patrol_status",
                "patrol_subject",
                "patrol_type__value",
                "participants",
                "patrol_purpose",
                "transport_type",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("obs_relocs") or {}),
        )
        .call()
    )

    persist_relocs = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            filename="patrol_relocations",
            df=obs_relocs,
            **(params.get("persist_relocs") or {}),
        )
        .call()
    )

    filter_foot_patrols = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_foot_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="Foot",
            df=obs_relocs,
            reset_index=True,
            **(params.get("filter_foot_patrols") or {}),
        )
        .call()
    )

    filter_vehicle_patrols = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_vehicle_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="Vehicle",
            df=obs_relocs,
            reset_index=False,
            **(params.get("filter_vehicle_patrols") or {}),
        )
        .call()
    )

    filter_motor_patrols = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_motor_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="transport_type",
            op="equal",
            value="Motorbike",
            df=obs_relocs,
            reset_index=False,
            **(params.get("filter_motor_patrols") or {}),
        )
        .call()
    )

    vehicle_trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("vehicle_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_vehicle_patrols,
            trajectory_segment_filter={
                "min_length_meters": 0.35,
                "max_length_meters": 5000.0,
                "max_time_secs": 18000.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 100.0,
                "min_speed_kmhr": 10.0,
            },
            **(params.get("vehicle_trajs") or {}),
        )
        .call()
    )

    motor_trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("motor_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_motor_patrols,
            trajectory_segment_filter={
                "min_length_meters": 0.35,
                "max_length_meters": 5000.0,
                "max_time_secs": 18000.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 100.0,
                "min_speed_kmhr": 10.0,
            },
            **(params.get("motor_trajs") or {}),
        )
        .call()
    )

    foot_trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("foot_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_foot_patrols,
            trajectory_segment_filter={
                "min_length_meters": 0.001,
                "max_length_meters": 5000.0,
                "max_time_secs": 14400.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 9.0,
                "min_speed_kmhr": 0.5,
            },
            **(params.get("foot_trajs") or {}),
        )
        .call()
    )

    temporal_foot_traj = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("temporal_foot_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=foot_trajs,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("temporal_foot_traj") or {}),
        )
        .call()
    )

    temporal_vehicle_traj = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("temporal_vehicle_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=vehicle_trajs,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("temporal_vehicle_traj") or {}),
        )
        .call()
    )

    temporal_motor_traj = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("temporal_motor_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=motor_trajs,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("temporal_motor_traj") or {}),
        )
        .call()
    )

    rename_foot_trajs = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_foot_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__created_at": "created_at",
                "extra__id": "id",
                "extra__participants": "participants",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_purpose": "patrol_purpose",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
                "extra__transport_type": "transport_type",
            },
            df=temporal_foot_traj,
            **(params.get("rename_foot_trajs") or {}),
        )
        .call()
    )

    rename_vehicle_trajs = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_vehicle_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__created_at": "created_at",
                "extra__id": "id",
                "extra__participants": "participants",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_purpose": "patrol_purpose",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
                "extra__transport_type": "transport_type",
            },
            df=temporal_vehicle_traj,
            **(params.get("rename_vehicle_trajs") or {}),
        )
        .call()
    )

    rename_motor_trajs = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_motor_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__created_at": "created_at",
                "extra__id": "id",
                "extra__participants": "participants",
                "extra__patrol_end_time": "patrol_end_time",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_purpose": "patrol_purpose",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_start_time": "patrol_start_time",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_title": "patrol_title",
                "extra__patrol_type": "patrol_type",
                "extra__patrol_type__value": "patrol_type_value",
                "extra__subject_id": "subject_id",
                "extra__transport_type": "transport_type",
            },
            df=temporal_motor_traj,
            **(params.get("rename_motor_trajs") or {}),
        )
        .call()
    )

    foot_patrol_metrics = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("foot_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_type_value"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            df=rename_foot_trajs,
            **(params.get("foot_patrol_metrics") or {}),
        )
        .call()
    )

    persist_foot_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_foot_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="foot_patrol_efforts",
            df=foot_patrol_metrics,
            **(params.get("persist_foot_df") or {}),
        )
        .call()
    )

    vehicle_patrol_metrics = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("vehicle_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_type_value"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            df=rename_vehicle_trajs,
            **(params.get("vehicle_patrol_metrics") or {}),
        )
        .call()
    )

    persist_vehicle_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_vehicle_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=vehicle_patrol_metrics,
            filename="vehicle_patrol_efforts",
            **(params.get("persist_vehicle_df") or {}),
        )
        .call()
    )

    motor_patrol_metrics = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("motor_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_type_value"],
            summary_params=[
                {
                    "display_name": "no_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "duration_hrs",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                },
                {
                    "display_name": "average_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
            ],
            reset_index=True,
            df=rename_motor_trajs,
            **(params.get("motor_patrol_metrics") or {}),
        )
        .call()
    )

    persist_motor_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_motor_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=motor_patrol_metrics,
            filename="motorbike_patrol_efforts",
            **(params.get("persist_motor_df") or {}),
        )
        .call()
    )

    foot_patrol_coverage = (
        task(create_patrol_coverage_grid)
        .validate()
        .set_task_instance_id("foot_patrol_coverage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajs=rename_foot_trajs,
            aoi=filter_conservancy_boundary,
            grid_cell_size=1000,
            keep_empty_cells=False,
            **(params.get("foot_patrol_coverage") or {}),
        )
        .call()
    )

    vehicle_patrol_coverage = (
        task(create_patrol_coverage_grid)
        .validate()
        .set_task_instance_id("vehicle_patrol_coverage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajs=rename_vehicle_trajs,
            aoi=filter_conservancy_boundary,
            grid_cell_size=1000,
            keep_empty_cells=False,
            **(params.get("vehicle_patrol_coverage") or {}),
        )
        .call()
    )

    motor_patrol_coverage = (
        task(create_patrol_coverage_grid)
        .validate()
        .set_task_instance_id("motor_patrol_coverage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajs=rename_motor_trajs,
            aoi=filter_conservancy_boundary,
            grid_cell_size=1000,
            keep_empty_cells=False,
            **(params.get("motor_patrol_coverage") or {}),
        )
        .call()
    )

    reproject_foot = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_foot")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=foot_patrol_coverage,
            target_crs="EPSG:4326",
            **(params.get("reproject_foot") or {}),
        )
        .call()
    )

    reproject_vehicle = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_vehicle")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=vehicle_patrol_coverage,
            target_crs="EPSG:4326",
            **(params.get("reproject_vehicle") or {}),
        )
        .call()
    )

    reproject_motor = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_motor")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=motor_patrol_coverage,
            target_crs="EPSG:4326",
            **(params.get("reproject_motor") or {}),
        )
        .call()
    )

    apply_foot_class_grid = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("apply_foot_class_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="unique_patrol_count",
            output_column_name="density_bins",
            label_options={"label_ranges": False, "label_decimals": 1},
            classification_options={"k": 5, "scheme": "equal_interval"},
            df=reproject_foot,
            **(params.get("apply_foot_class_grid") or {}),
        )
        .call()
    )

    apply_foot_grid_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_foot_grid_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn",
            output_column_name="density_colors",
            df=apply_foot_class_grid,
            **(params.get("apply_foot_grid_colormap") or {}),
        )
        .call()
    )

    generate_foot_grid_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("generate_foot_grid_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.35,
                "get_line_width": 0.95,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Grid Cell Visits",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            geodataframe=apply_foot_grid_colormap,
            data_url=None,
            **(params.get("generate_foot_grid_layer") or {}),
        )
        .call()
    )

    combine_foot_patrol = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_foot_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[create_parcels_layer, create_conservancy_layer],
            grouped_layers=generate_foot_grid_layer,
            **(params.get("combine_foot_patrol") or {}),
        )
        .call()
    )

    draw_foot_map = (
        task(draw_map_2)
        .validate()
        .set_task_instance_id("draw_foot_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_foot_patrol,
            view_state=gdf_image_extent,
            **(params.get("draw_foot_map") or {}),
        )
        .call()
    )

    persist_foot_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_foot_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_foot_map,
            filename="foot_patrol_map.html",
            **(params.get("persist_foot_urls") or {}),
        )
        .call()
    )

    convert_foot_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_foot_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_foot_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_foot_png") or {}),
        )
        .call()
    )

    foot_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("foot_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Foot Patrol Coverage Map",
            data=persist_foot_urls,
            **(params.get("foot_map_widget") or {}),
        )
        .call()
    )

    apply_vh_class_grid = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("apply_vh_class_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="unique_patrol_count",
            output_column_name="density_bins",
            label_options={"label_ranges": False, "label_decimals": 1},
            classification_options={"k": 5, "scheme": "equal_interval"},
            df=reproject_vehicle,
            **(params.get("apply_vh_class_grid") or {}),
        )
        .call()
    )

    apply_vh_grid_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_vh_grid_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn",
            output_column_name="density_colors",
            df=apply_vh_class_grid,
            **(params.get("apply_vh_grid_colormap") or {}),
        )
        .call()
    )

    generate_vh_grid_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("generate_vh_grid_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.35,
                "get_line_width": 0.95,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Grid Cell Visits",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            geodataframe=apply_vh_grid_colormap,
            data_url=None,
            **(params.get("generate_vh_grid_layer") or {}),
        )
        .call()
    )

    combine_vh_patrol = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_vh_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[create_parcels_layer, create_conservancy_layer],
            grouped_layers=generate_vh_grid_layer,
            **(params.get("combine_vh_patrol") or {}),
        )
        .call()
    )

    draw_vh_map = (
        task(draw_map_2)
        .validate()
        .set_task_instance_id("draw_vh_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_vh_patrol,
            view_state=gdf_image_extent,
            **(params.get("draw_vh_map") or {}),
        )
        .call()
    )

    persist_vh_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_vh_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_vh_map,
            filename="vehicle_patrol_map.html",
            **(params.get("persist_vh_urls") or {}),
        )
        .call()
    )

    convert_vh_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_vh_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_vh_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_vh_png") or {}),
        )
        .call()
    )

    vh_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("vh_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Vehicle Patrol Coverage Map",
            data=persist_vh_urls,
            **(params.get("vh_map_widget") or {}),
        )
        .call()
    )

    apply_mr_class_grid = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("apply_mr_class_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="unique_patrol_count",
            output_column_name="density_bins",
            label_options={"label_ranges": False, "label_decimals": 1},
            classification_options={"k": 5, "scheme": "equal_interval"},
            df=reproject_motor,
            **(params.get("apply_mr_class_grid") or {}),
        )
        .call()
    )

    apply_mr_grid_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_mr_grid_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn",
            output_column_name="density_colors",
            df=apply_mr_class_grid,
            **(params.get("apply_mr_grid_colormap") or {}),
        )
        .call()
    )

    generate_mr_grid_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("generate_mr_grid_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.35,
                "get_line_width": 0.95,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Grid Cell Visits",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            geodataframe=apply_mr_grid_colormap,
            data_url=None,
            **(params.get("generate_mr_grid_layer") or {}),
        )
        .call()
    )

    combine_mr_patrol = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_mr_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[create_parcels_layer, create_conservancy_layer],
            grouped_layers=generate_mr_grid_layer,
            **(params.get("combine_mr_patrol") or {}),
        )
        .call()
    )

    draw_mr_map = (
        task(draw_map_2)
        .validate()
        .set_task_instance_id("draw_mr_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_mr_patrol,
            view_state=gdf_image_extent,
            **(params.get("draw_mr_map") or {}),
        )
        .call()
    )

    persist_mr_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_mr_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_mr_map,
            filename="motor_patrol_map.html",
            **(params.get("persist_mr_urls") or {}),
        )
        .call()
    )

    convert_mr_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_mr_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_mr_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_mr_png") or {}),
        )
        .call()
    )

    mr_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("mr_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Motorbike Patrol Coverage Map",
            data=persist_mr_urls,
            **(params.get("mr_map_widget") or {}),
        )
        .call()
    )

    concat_dataframes = (
        task(concatenate_dataframes)
        .validate()
        .set_task_instance_id("concat_dataframes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            list_df=[rename_foot_trajs, rename_vehicle_trajs, rename_motor_trajs],
            axis=0,
            join="outer",
            ignore_index=True,
            keys=None,
            levels=None,
            names=None,
            verify_integrity=False,
            sort=False,
            copy=None,
            **(params.get("concat_dataframes") or {}),
        )
        .call()
    )

    overall_patrol_coverage = (
        task(create_patrol_coverage_grid)
        .validate()
        .set_task_instance_id("overall_patrol_coverage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajs=concat_dataframes,
            aoi=filter_conservancy_boundary,
            grid_cell_size=1000,
            keep_empty_cells=False,
            **(params.get("overall_patrol_coverage") or {}),
        )
        .call()
    )

    reproject_overall = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_overall")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=overall_patrol_coverage,
            target_crs="EPSG:4326",
            **(params.get("reproject_overall") or {}),
        )
        .call()
    )

    apply_ov_class_grid = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("apply_ov_class_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="unique_patrol_count",
            output_column_name="density_bins",
            label_options={"label_ranges": False, "label_decimals": 1},
            classification_options={"k": 5, "scheme": "equal_interval"},
            df=reproject_overall,
            **(params.get("apply_ov_class_grid") or {}),
        )
        .call()
    )

    apply_ov_grid_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_ov_grid_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn",
            output_column_name="density_colors",
            df=apply_ov_class_grid,
            **(params.get("apply_ov_grid_colormap") or {}),
        )
        .call()
    )

    generate_ov_grid_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("generate_ov_grid_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_colors",
                "get_line_color": [0, 0, 0],
                "opacity": 0.35,
                "get_line_width": 0.95,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Grid Cell Visits",
                "label_column": "density_bins",
                "color_column": "density_colors",
            },
            geodataframe=apply_ov_grid_colormap,
            data_url=None,
            **(params.get("generate_ov_grid_layer") or {}),
        )
        .call()
    )

    combine_ov_patrol = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_ov_patrol")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[create_parcels_layer, create_conservancy_layer],
            grouped_layers=generate_ov_grid_layer,
            **(params.get("combine_ov_patrol") or {}),
        )
        .call()
    )

    draw_ov_map = (
        task(draw_map_2)
        .validate()
        .set_task_instance_id("draw_ov_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_ov_patrol,
            view_state=gdf_image_extent,
            **(params.get("draw_ov_map") or {}),
        )
        .call()
    )

    persist_ov_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_ov_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_ov_map,
            filename="overall_patrol_map.html",
            **(params.get("persist_ov_urls") or {}),
        )
        .call()
    )

    convert_ov_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_ov_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_ov_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_ov_png") or {}),
        )
        .call()
    )

    ov_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("ov_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Overall Patrol Coverage Map",
            data=persist_ov_urls,
            **(params.get("ov_map_widget") or {}),
        )
        .call()
    )

    persist_trajectories_data = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_trajectories_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            df=reproject_overall,
            filename="patrol_trajectories",
            **(params.get("persist_trajectories_data") or {}),
        )
        .call()
    )

    ranger_patrol_metrics = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("ranger_patrol_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["participants"],
            summary_params=[
                {
                    "display_name": "number_of_patrols",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": 0,
                },
                {
                    "display_name": "distance_km",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "duration_hours",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 2,
                },
            ],
            reset_index=True,
            df=concat_dataframes,
            **(params.get("ranger_patrol_metrics") or {}),
        )
        .call()
    )

    fill_participants = (
        task(fill_missing_values)
        .validate()
        .set_task_instance_id("fill_participants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=ranger_patrol_metrics,
            subset=["participants"],
            value="Undefined",
            **(params.get("fill_participants") or {}),
        )
        .call()
    )

    no_of_patrols_int = (
        task(convert_columns_to_int)
        .validate()
        .set_task_instance_id("no_of_patrols_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fill_participants,
            columns=["number_of_patrols"],
            errors="coerce",
            fill_value=0,
            **(params.get("no_of_patrols_int") or {}),
        )
        .call()
    )

    persist_total_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_total_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=no_of_patrols_int,
            filename="overall_patrol_efforts",
            **(params.get("persist_total_df") or {}),
        )
        .call()
    )

    patrol_efforts_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("patrol_efforts_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=no_of_patrols_int,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Overall Patrol Efforts",
            **(params.get("patrol_efforts_table_html") or {}),
        )
        .call()
    )

    patrol_efforts_table_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_efforts_table_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=patrol_efforts_table_html,
            filename="overall_patrol_efforts_table.html",
            **(params.get("patrol_efforts_table_url") or {}),
        )
        .call()
    )

    patrol_efforts_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_efforts_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Overall Patrol Efforts",
            data=patrol_efforts_table_url,
            **(params.get("patrol_efforts_table_widget") or {}),
        )
        .call()
    )

    reproject_conservancy = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_conservancy")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=filter_conservancy_boundary,
            target_crs="EPSG:3857",
            **(params.get("reproject_conservancy") or {}),
        )
        .call()
    )

    compute_cons_occupancy = (
        task(compute_patrol_occupancy)
        .validate()
        .set_task_instance_id("compute_cons_occupancy")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            conservancies=reproject_conservancy,
            patrol_coverage=overall_patrol_coverage,
            **(params.get("compute_cons_occupancy") or {}),
        )
        .call()
    )

    persist_occupancy_df = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_occupancy_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=compute_cons_occupancy,
            filename="patrol_coverage",
            **(params.get("persist_occupancy_df") or {}),
        )
        .call()
    )

    occupancy_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("occupancy_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=compute_cons_occupancy,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Conservancy Patrol Occupancy",
            **(params.get("occupancy_table_html") or {}),
        )
        .call()
    )

    occupancy_table_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("occupancy_table_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=occupancy_table_html,
            filename="patrol_coverage_table.html",
            **(params.get("occupancy_table_url") or {}),
        )
        .call()
    )

    occupancy_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("occupancy_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Conservancy Patrol Occupancy",
            data=occupancy_table_url,
            **(params.get("occupancy_table_widget") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                foot_map_widget,
                vh_map_widget,
                mr_map_widget,
                ov_map_widget,
                events_chart_widget,
                patrol_summary_table_widget,
                patrol_efforts_table_widget,
                occupancy_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
